events {}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    gzip on;
    gzip_types text/plain application/xml text/css text/javascript application/javascript application/json;
    gzip_min_length 256;

    server {
        listen 80;
        server_name _;

        root /usr/share/nginx/html;
        index index.html;

        # Browser caching for static assets
        location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|otf)$ {
            expires 30d;
            access_log off;
            add_header Cache-Control "public";
        }

        # Default location for Hugo content
        location / {
            try_files $uri $uri/ =404;
        }
    }
}
